# Generated by Django 6.0.3 on 2026-03-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('checked_in', 'Checked In'), ('screened', 'Screened'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='pending', max_length=20),
        ),
    ]
