# Generated by Django 6.0.3 on 2026-04-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_deposit_amount_booking_deposit_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('awaiting_eligibility', 'Awaiting Eligibility'), ('pending', 'Pending'), ('deposit_pending', 'Deposit Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('ineligible', 'Ineligible'), ('checked_in', 'Checked In'), ('ready_to_inject', 'Ready to Inject'), ('in_observation', 'In Observation'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='pending', max_length=20),
        ),
    ]
