# Generated by Django 6.0.3 on 2026-03-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_user_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên vị trí')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vị trí bảo quản',
                'verbose_name_plural': 'Vị trí bảo quản',
                'db_table': 'assets_storage_location',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Tên nhà cung cấp')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'db_table': 'assets_supplier',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên vắc-xin')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Nhà sản xuất')),
                ('batch_number', models.CharField(max_length=50, unique=True, verbose_name='Số lô')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn')),
                ('minimum_stock', models.PositiveIntegerField(default=10, verbose_name='Tồn tối thiểu')),
                ('expiration_date', models.DateField(verbose_name='Hạn sử dụng')),
                ('storage_temperature', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nhiệt độ bảo quản')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccines', to='assets.storagelocation', verbose_name='Vị trí bảo quản')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccines', to='assets.supplier', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Vắc-xin',
                'verbose_name_plural': 'Vắc-xin',
                'db_table': 'assets_vaccine',
            },
        ),
        migrations.CreateModel(
            name='StockImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng nhập')),
                ('import_date', models.DateField(verbose_name='Ngày nhập')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_imports', to='authentication.user', verbose_name='Người tạo')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='assets.supplier', verbose_name='Nhà cung cấp')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='assets.vaccine', verbose_name='Vắc-xin')),
            ],
            options={
                'verbose_name': 'Phiếu nhập kho',
                'verbose_name_plural': 'Phiếu nhập kho',
                'db_table': 'assets_stock_import',
            },
        ),
        migrations.CreateModel(
            name='StockExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng xuất')),
                ('export_date', models.DateField(verbose_name='Ngày xuất')),
                ('destination', models.CharField(max_length=150, verbose_name='Nơi nhận')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_exports', to='authentication.user', verbose_name='Người tạo')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='assets.vaccine', verbose_name='Vắc-xin')),
            ],
            options={
                'verbose_name': 'Phiếu xuất kho',
                'verbose_name_plural': 'Phiếu xuất kho',
                'db_table': 'assets_stock_export',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('increase', 'Tăng'), ('decrease', 'Giảm')], max_length=20, verbose_name='Loại điều chỉnh')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng điều chỉnh')),
                ('reason', models.CharField(max_length=255, verbose_name='Lý do')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to='authentication.user', verbose_name='Người tạo')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='assets.vaccine', verbose_name='Vắc-xin')),
            ],
            options={
                'verbose_name': 'Phiếu điều chỉnh kho',
                'verbose_name_plural': 'Phiếu điều chỉnh kho',
                'db_table': 'assets_stock_adjustment',
            },
        ),
    ]
