# Generated by Django 6.0.3 on 2026-04-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_stockexport_export_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Giá niêm yết'),
        ),
    ]
