# Generated by Django 6.0.3 on 2026-03-23 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_status'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('blood_pressure', models.CharField(max_length=50)),
                ('is_eligible', models.BooleanField()),
                ('doctor_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_result', to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_id', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=50)),
                ('injected_by', models.CharField(max_length=100)),
                ('injection_time', models.DateTimeField(auto_now_add=True)),
                ('dose_number', models.PositiveSmallIntegerField(default=1)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_log', to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='PostInjectionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_status', models.CharField(choices=[('Normal', 'Normal'), ('Mild', 'Mild'), ('Severe', 'Severe')], default='Normal', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vaccination_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_tracking', to='medical.vaccinationlog')),
            ],
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
