# Generated by Django 6.0.3 on 2026-04-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_legacy_vaccine_code_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningresult',
            name='decision',
            field=models.CharField(choices=[('eligible', 'Eligible'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='eligible', max_length=20),
        ),
        migrations.AlterField(
            model_name='screeningresult',
            name='is_eligible',
            field=models.BooleanField(default=True),
        ),
    ]
