# Generated by Django 6.0.3 on 2026-04-29 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_add_doctor_role'),
        ('booking', '0006_alter_booking_status'),
        ('medical', '0007_fix_sqlite_post_tracking_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescreeningdeclaration',
            name='current_health_issue_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescreeningdeclaration',
            name='had_recent_vaccination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescreeningdeclaration',
            name='has_current_health_issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescreeningdeclaration',
            name='has_pregnancy_or_breastfeeding_consideration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescreeningdeclaration',
            name='has_severe_allergy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescreeningdeclaration',
            name='immunosuppressive_medication_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescreeningdeclaration',
            name='pregnancy_or_breastfeeding_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescreeningdeclaration',
            name='recent_vaccination_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescreeningdeclaration',
            name='severe_allergy_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescreeningdeclaration',
            name='uses_immunosuppressive_medication',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OnlineEligibilityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('eligible', 'Eligible'), ('delayed', 'Delayed'), ('ineligible', 'Ineligible')], default='eligible', max_length=20)),
                ('doctor_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_review', to='booking.booking')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_eligibility_reviews', to='authentication.user')),
            ],
        ),
    ]
